const throwErr = () => increment(4);
